footprint: [[0.47, -0.35], [0.47, 0.35], [-0.47, 0.35], [-0.47, -0.35]]

update_frequency: 10.0
publish_frequency: 10.0

obstacle_layer:
  observation_sources: scan rgbd_camera
  scan: {topic: scan, sensor_frame: laser_link, data_type: LaserScan, clearing: true, marking: true, obstacle_range: 15.0, raytrace_range: 20.0, inf_is_valid: true, min_obstacle_height: 0.1, max_obstacle_height: 2.0}
  rgbd_camera: {topic: camera/depth_registered/points, sensor_frame: camera_color_optical_frame, data_type: PointCloud2, clearing: true, marking: true, obstacle_range: 5.0, raytrace_range: 6.0, inf_is_valid: true, min_obstacle_height: 0.25, max_obstacle_height: 0.25}