pub_rate: 1.0
analyzers:
  scout:
    type: diagnostic_aggregator/GenericAnalyzer
    path: Scout
    find_and_remove_prefix: 'scout_base_node'
    timeout: 5.0
    contains: [
      'scout_base_node: Base',
      'scout_base_node: Battery',
      'scout_base_node: Current',
      'scout_base_node: Temperature',
      'scout_base_node: Communication',
      'scout_base_node: Light']
  teleop:
    type: diagnostic_aggregator/AnalyzerGroup
    path: Teleop
    analyzers:
      joystick:
        type: diagnostic_aggregator/GenericAnalyzer
        path: Bluetooth Joystick
        find_and_remove_prefix: 'joy_node'
        timeout: 5.0
        expected: [
          'joy_node: Joystick Driver Status']